version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgre:root@db/estacionamentos_api

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: estacionamentos_api
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: root